### ISSUE TITLE
Card css is targeting global wildcard pseudo elements

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/uitk#193]
Card css shouldn't target wildcard all pseudo elements 

```css 
.uitkCard *, *:before, *:after {
    box-sizing: inherit;
}
```
